### PR TITLE
Mention direct DELEG queries as a potential resolution strategy

### PR DESCRIPTION
**Pull request by bemasc**
This strategy was discussed earlier but seems to have been lost in the text.

### CODE REVIEW

**Comment by paulehoffman** [comment]
This seems to have been overcome by later pull requests that were accepted. Maybe it should be closed, and reopened against the current wording if still needed.

**Comment by bemasc** [comment]
@paulehoffman I've updated this PR to clear the merge conflict.

**Comment by paulehoffman** [comment]
This looks OK. That is, I think the additional proposal is terrible, but at least there are no merge conflicts.

**Comment by bemasc** [comment]
This is superseded by the discussion in #30.

**Pull request closed without merging**
